Repository pycontribs/ruyaml, pull requests merged in 2021-12, with the labels that each got.

#65 Upgrade GHA pipelines
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#66 Bump linters
  .pre-commit-config.yaml
  _test/test_yamlfile.py
  lib/ruyaml/representer.py
Labels: skip-changelog

#67 Enable support for py310
  .github/workflows/tox.yml
  setup.cfg
  tox.ini
Labels: enhancement

#68 Add check workflow
  .github/workflows/tox.yml
Labels: skip-changelog

#69 Upstream 0.17.17
  CHANGES
  README.rst
  _doc/_static/pypi.svg
  lib/ruyaml/comments.py
  lib/ruyaml/constructor.py
  lib/ruyaml/util.py
Labels: refactoring

#70 Add codeowners file
  .github/CODEOWNERS
Labels: skip-changelog

#71 Upgrade packaging testing
  tox.ini
Labels: skip-changelog

#73 Document how to do an upstream merge
  _doc/index.rst
  _doc/upmerge.rst
Labels: bug, docs

#72 Remove setup.py
  MANIFEST.in
  _doc/contributing.rst
  _doc/contributing.ryd
  setup.cfg
  setup.py
  tox.ini
Labels: enhancement

#74 Move pytest config to pyproject.toml
  pyproject.toml
  tox.ini
Labels: skip-changelog

#80 Upgrade mypy
  .pre-commit-config.yaml
  _test/lib/test_all.py
  _test/lib/test_emitter.py
  _test/lib/test_errors.py
  _test/lib/test_input_output.py
  _test/lib/test_mark.py
  _test/lib/test_reader.py
  _test/lib/test_recursive.py
  _test/lib/test_resolver.py
  _test/lib/test_structure.py
  _test/test_z_data.py
  _test/test_z_olddata.py
  lib/ruyaml/cyaml.py
  lib/ruyaml/representer.py
  lib/ruyaml/scalarstring.py
  lib/ruyaml/tokens.py
Labels: skip-changelog

#81 Bump linters
  .pre-commit-config.yaml
  _test/lib/test_all.py
  _test/lib/test_emitter.py
  _test/lib/test_errors.py
  _test/lib/test_input_output.py
  _test/lib/test_mark.py
  _test/lib/test_reader.py
  _test/lib/test_recursive.py
  _test/lib/test_resolver.py
  _test/lib/test_structure.py
  _test/test_z_data.py
  _test/test_z_olddata.py
  lib/ruyaml/cyaml.py
  pyproject.toml
Labels: skip-changelog
